# Generated by Django 3.1.1 on 2020-09-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thumbnail_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddIndex(
            model_name='video_info',
            index=models.Index(fields=['-published_at'], name='youtubeFeed_publish_424984_idx'),
        ),
    ]
